# Generated by Django 3.2.6 on 2025-03-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20250313_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_type',
            field=models.IntegerField(blank=True, verbose_name='client_type'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='gender_id',
            field=models.IntegerField(blank=True, verbose_name='gender_id'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(blank=True, max_length=500, verbose_name='Phone'),
        ),
    ]
