# Generated by Django 3.2.6 on 2025-03-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_clients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amout',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
