# Generated by Django 3.2.6 on 2025-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_orderproduct_amout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
