# Generated by Django 3.2.6 on 2025-04-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20250402_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='products',
            name='volume_name_eng',
        ),
        migrations.RemoveField(
            model_name='products',
            name='volume_name_uz',
        ),
        migrations.AlterField(
            model_name='products',
            name='primechaniye_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='primechaniye_eng'),
        ),
        migrations.AlterField(
            model_name='products',
            name='primechaniye_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='primechaniye_ru'),
        ),
        migrations.AlterField(
            model_name='products',
            name='primechaniye_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='primechaniye_uz'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sostav',
            field=models.CharField(blank=True, max_length=500, verbose_name='sostav'),
        ),
    ]
