# Generated by Django 3.2.6 on 2025-04-27 11:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20250427_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(blank=True, max_length=500, verbose_name='title_uz')),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='title_ru')),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=500, verbose_name='title_eng')),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='actual/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actual',
                'verbose_name_plural': 'Актуальные',
            },
        ),
        migrations.AddField(
            model_name='stories',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.brand', verbose_name='Brand ID'),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_eng',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stories',
            name='categoty_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.category', verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(upload_to='stories/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.products', verbose_name='Products ID'),
        ),
        migrations.AddField(
            model_name='stories',
            name='actua_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.actual', verbose_name='Actual ID'),
        ),
    ]
