# Generated by Django 3.2.6 on 2025-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_products_bestsellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_bestsellers',
            field=models.BooleanField(default=False),
        ),
    ]
