# Generated by Django 3.2.6 on 2025-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0041_mobiledocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
