# Generated by Django 3.2.6 on 2025-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0042_slider_dark_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='dark_mode',
            new_name='get_color',
        ),
        migrations.AddField(
            model_name='slider',
            name='text_color_white',
            field=models.BooleanField(default=True),
        ),
    ]
