# Generated by Django 3.2.6 on 2025-05-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0044_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='bestsellers',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_bestsellers',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='gift_cart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='hit',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='volume_type',
            field=models.CharField(blank=True, choices=[('МЛ', 'ОБЪЁМ / МЛ'), ('ШТ', 'КОЛИЧЕСТВО / ШТ'), ('Г', 'ВЕС / Г')], default='МЛ', max_length=10),
        ),
    ]
