# Generated by Django 3.2.6 on 2025-05-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_auto_20250515_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.new', verbose_name='News ID'),
        ),
    ]
