# Generated by Django 3.2.6 on 2025-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0055_auto_20250527_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='header_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='header_eng'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='header_ru'),
        ),
        migrations.AddField(
            model_name='slider',
            name='header_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='header_uz'),
        ),
    ]
