# Generated by Django 3.2.6 on 2025-03-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20250313_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParrentProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(blank=True, max_length=500, verbose_name='title_uz')),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='title_ru')),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=500, verbose_name='title_eng')),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='movies.products')),
            ],
        ),
    ]
