# Generated by Django 3.2.6 on 2025-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_parrentproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parrentproduct',
            name='description_eng',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='title_eng',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='parrentproduct',
            name='video',
        ),
        migrations.AddField(
            model_name='parrentproduct',
            name='volume',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='parrentproduct',
            name='volume_name_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_eng'),
        ),
        migrations.AddField(
            model_name='parrentproduct',
            name='volume_name_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_ru'),
        ),
        migrations.AddField(
            model_name='parrentproduct',
            name='volume_name_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_uz'),
        ),
    ]
