# Generated by Django 3.2.6 on 2025-03-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20250313_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='volume',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume'),
        ),
        migrations.AddField(
            model_name='products',
            name='volume_name_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_eng'),
        ),
        migrations.AddField(
            model_name='products',
            name='volume_name_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_ru'),
        ),
        migrations.AddField(
            model_name='products',
            name='volume_name_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_uz'),
        ),
    ]
