# Generated by Django 3.2.6 on 2025-03-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_orderproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='amout',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
