# Generated by Django 3.2.6 on 2025-03-22 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20250322_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='amout',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
