# Generated by Django 3.2.6 on 2025-03-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20250322_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
