# Generated by Django 3.2.6 on 2025-04-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20250322_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forwhom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Forwhom',
                'verbose_name_plural': 'Для кого',
            },
        ),
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ProductArea',
                'verbose_name_plural': 'Oбласть применения',
            },
        ),
        migrations.CreateModel(
            name='Skintype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Skintype',
                'verbose_name_plural': 'Тип кожи',
            },
        ),
        migrations.AlterModelOptions(
            name='aiforsales',
            options={'verbose_name': 'AIforSales', 'verbose_name_plural': 'ИИ для продаж'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Clients', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Gift', 'verbose_name_plural': 'Подарочные карты'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'MainPage', 'verbose_name_plural': 'Настройка главной страницы приложения '},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'New', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'OrderProduct', 'verbose_name_plural': 'Список заказанных продуктов'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='parrentproduct',
            options={'verbose_name': 'ParrentProduct', 'verbose_name_plural': 'Родительский Продукт'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'ProductType', 'verbose_name_plural': 'Типы продукта'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='searchstory',
            options={'verbose_name': 'SearchStory', 'verbose_name_plural': 'История поиска'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Stories', 'verbose_name_plural': 'Сторисы'},
        ),
        migrations.AlterModelOptions(
            name='toptypes',
            options={'verbose_name': 'TopTypes', 'verbose_name_plural': 'Топ типы товаров'},
        ),
        migrations.AddField(
            model_name='products',
            name='primechaniye_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_eng'),
        ),
        migrations.AddField(
            model_name='products',
            name='primechaniye_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_ru'),
        ),
        migrations.AddField(
            model_name='products',
            name='primechaniye_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_uz'),
        ),
        migrations.AddField(
            model_name='products',
            name='sostav',
            field=models.CharField(blank=True, max_length=500, verbose_name='volume_name_uz'),
        ),
        migrations.AddField(
            model_name='products',
            name='for_whom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.forwhom', verbose_name='Forwhom'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.productarea', verbose_name='ProductArea ID'),
        ),
        migrations.AddField(
            model_name='products',
            name='skin_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.skintype', verbose_name='Skintype ID'),
        ),
    ]
