# Generated by Django 3.2.6 on 2025-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20250402_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='primechaniye_eng',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='primechaniye_ru',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='primechaniye_uz',
            field=models.TextField(),
        ),
    ]
