# Generated by Django 3.2.6 on 2025-04-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20250402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='volume_type',
            field=models.CharField(choices=[('МЛ', 'ОБЪЁМ / МЛ'), ('ШТ', 'КОЛИЧЕСТВО / ШТ'), ('Г', 'ВЕС / Г')], default='МЛ', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.aiforsales', verbose_name='ИИ для продаж'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='products',
            name='categoty_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='movies.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='for_whom_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.forwhom', verbose_name='Для кого '),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_area_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.productarea', verbose_name='Область применения'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.producttype', verbose_name='Тип продукта '),
        ),
        migrations.AlterField(
            model_name='products',
            name='skin_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.skintype', verbose_name='Тип Кожи'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название eng'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название ru'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='Название uz'),
        ),
        migrations.AlterField(
            model_name='products',
            name='top_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.toptypes', verbose_name='Топ типы продукта '),
        ),
        migrations.AlterField(
            model_name='products',
            name='volume_name_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='объем'),
        ),
    ]
