# Generated by Django 3.2.6 on 2025-04-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20250411_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='age',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='gmail',
        ),
        migrations.AddField(
            model_name='clients',
            name='birth_data',
            field=models.CharField(blank=True, max_length=500, verbose_name='birth_data'),
        ),
        migrations.AddField(
            model_name='clients',
            name='surname',
            field=models.CharField(blank=True, max_length=500, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='city'),
        ),
    ]
