# Generated by Django 3.2.6 on 2025-04-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20250418_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_date'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_date_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='delivery_date_type'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='payment_type'),
        ),
        migrations.AddField(
            model_name='orders',
            name='promocode_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='surname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('promo_type', models.IntegerField(blank=True, null=True)),
                ('promo_sum', models.IntegerField(blank=True, null=True)),
                ('promo_usage_type', models.IntegerField(blank=True, null=True)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.clients', verbose_name='Clients ID')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promo kod',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.promo', verbose_name='Promo ID'),
        ),
    ]
