# Generated by Django 3.2.6 on 2025-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20250419_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_date_type',
        ),
        migrations.AddField(
            model_name='orders',
            name='type_delivery_date',
            field=models.IntegerField(blank=True, null=True, verbose_name='type_delivery_date'),
        ),
    ]
