# Generated by Django 3.2.6 on 2025-04-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_auto_20250419_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_date',
        ),
    ]
