# Generated by Django 3.2.6 on 2025-04-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_orders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='delivery_date'),
        ),
    ]
