# Generated by Django 3.2.6 on 2025-04-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_orders_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='all_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='promocode_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
