# Generated by Django 3.2.6 on 2025-04-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20250423_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hairtype',
                'verbose_name_plural': 'Тип волос',
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(blank=True, max_length=500, verbose_name='title_uz')),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='title_ru')),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('title_eng', models.CharField(blank=True, max_length=500, verbose_name='title_eng')),
                ('description_eng', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ProductBundle',
                'verbose_name_plural': 'Связка товара',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='primechaniye_eng',
        ),
        migrations.RemoveField(
            model_name='products',
            name='primechaniye_ru',
        ),
        migrations.RemoveField(
            model_name='products',
            name='primechaniye_uz',
        ),
        migrations.AlterField(
            model_name='products',
            name='sostav',
            field=models.CharField(blank=True, max_length=1000, verbose_name='sostav'),
        ),
        migrations.AddField(
            model_name='products',
            name='hair_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.hairtype', verbose_name='Тип волос'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_bundle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.productbundle', verbose_name='Связка товара '),
        ),
    ]
