# Generated by Django 3.2.6 on 2025-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20250427_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiforsales',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiforsales',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='title_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hairtype',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productarea',
            name='title_eng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productarea',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productarea',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
