# Generated by Django 3.2.6 on 2025-04-27 13:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_auto_20250427_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description_eng',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
