# Generated by Django 3.2.6 on 2025-04-27 13:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0029_auto_20250427_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='description_eng',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
