# Generated by Django 3.2.6 on 2025-04-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_auto_20250427_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
