# Generated by Django 3.2.6 on 2025-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_products_hit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hit',
            field=models.BooleanField(default=False),
        ),
    ]
