# Generated by Django 3.2.6 on 2025-04-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0033_alter_products_hit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='actua_id',
            new_name='actual_id',
        ),
    ]
