# Generated by Django 3.2.6 on 2025-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0034_rename_actua_id_stories_actual_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actual',
            name='count',
            field=models.CharField(blank=True, max_length=500, verbose_name='count'),
        ),
    ]
