# Generated by Django 3.2.6 on 2025-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_actual_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='bestsellers',
            field=models.BooleanField(default=False),
        ),
    ]
