# Generated by Django 3.2.6 on 2025-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_products_brand_bestsellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='review/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='review/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='review/'),
        ),
    ]
