# Generated by Django 3.2.6 on 2025-05-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_auto_20250501_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='title_bottom_eng',
            field=models.CharField(blank=True, max_length=500, verbose_name='title_bottom_eng'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_bottom_ru',
            field=models.CharField(blank=True, max_length=500, verbose_name='title_bottom_ru'),
        ),
        migrations.AddField(
            model_name='new',
            name='title_bottom_uz',
            field=models.CharField(blank=True, max_length=500, verbose_name='title_bottom_uz'),
        ),
        migrations.AddField(
            model_name='products',
            name='gift_cart',
            field=models.BooleanField(default=False),
        ),
    ]
