# Generated by Django 3.2.6 on 2025-05-05 15:36

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0040_category_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_uz', models.CharField(blank=True, max_length=500, verbose_name='title_uz')),
                ('title_bottom_uz', models.CharField(blank=True, max_length=500, verbose_name='title_bottom_uz')),
                ('description_uz', django_quill.fields.QuillField(blank=True)),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='title_ru')),
                ('title_bottom_ru', models.CharField(blank=True, max_length=500, verbose_name='title_bottom_ru')),
                ('description_ru', django_quill.fields.QuillField(blank=True)),
                ('title_eng', models.CharField(blank=True, max_length=500, verbose_name='title_eng')),
                ('title_bottom_eng', models.CharField(blank=True, max_length=500, verbose_name='title_bottom_eng')),
                ('description_eng', django_quill.fields.QuillField(blank=True)),
            ],
            options={
                'verbose_name': 'MobileDocuments',
                'verbose_name_plural': 'MobileDocuments',
            },
        ),
    ]
