# Generated by Django 3.2.6 on 2025-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0043_auto_20250511_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
