# Generated by Django 3.2.6 on 2025-05-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_alter_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='products',
            field=models.ManyToManyField(blank=True, to='movies.Products', verbose_name='Список продуктов'),
        ),
        migrations.AddField(
            model_name='slider',
            name='brand_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.brand', verbose_name='Brand ID'),
        ),
    ]
