# Generated by Django 3.2.6 on 2025-05-13 13:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_auto_20250512_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledocuments',
            name='description_eng',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledocuments',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledocuments',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_eng',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
