# Generated by Django 3.2.6 on 2025-05-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0049_auto_20250513_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToken',
            fields=[
                ('token', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('phone_brand', models.CharField(max_length=500)),
                ('os_name', models.CharField(max_length=500)),
                ('client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.clients', verbose_name='client_id')),
            ],
            options={
                'verbose_name': 'NotificationToken',
                'verbose_name_plural': 'NotificationToken',
            },
        ),
    ]
