# Generated by Django 3.2.6 on 2025-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0050_notificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='lang',
            field=models.CharField(blank=True, max_length=500, verbose_name='lang'),
        ),
    ]
