# Generated by Django 3.2.6 on 2025-05-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0051_clients_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Промокод на доставку'), (2, 'Промокод на сумму товара')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_usage_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Единоразово'), (2, 'Бесконечный')], default=1, null=True),
        ),
    ]
