# Generated by Django 3.2.6 on 2025-05-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_slider_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='promo_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Промокод на доставку'), (2, 'Промокод на сумму товара'), (3, 'Промокод на % сумму товара')], default=1, null=True),
        ),
    ]
