# Generated by Django 3.2.6 on 2025-05-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0054_auto_20250517_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_ru', models.CharField(blank=True, max_length=500, verbose_name='title_ru')),
                ('color', models.CharField(blank=True, max_length=500, verbose_name='color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='product_color_type',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.productcolor', verbose_name='Product color '),
        ),
    ]
